### ISSUE TITLE
cl20 cl21 cl22 device_execution/enqueue_flags data race

### ISSUE THREAD

**Issue by alexbatashev** [KhronosGroup/OpenCL-CTS#40]
At least four of tests' kernels run into data race:
- enqueue_flags_wait_work_group_simple
- enqueue_flags_wait_work_group_event
- enqueue_flags_wait_work_group_local
- enqueue_flags_wait_work_group_event_local

res[gid] is being written by get_num_groups()/get_local_size() threads. And if one of these thread put 2 to the array cell, it still may be overwritten with 1 by another thread. Thus, the test doesn't really test anything.

**Comment by b-sumner** [comment]
gid == get_group_id(0), lid == get_local_id(0).

With the guard "if (lid == 0 && gid == group_id)" protecting it, I only see one thread able to write to res[gid].

The barrier flag should definitely be CLK_GLOBAL_MEM_FENCE.

**Comment by alexbatashev** [comment]
@b-sumner 
Let's have a look at line [590](https://github.com/KhronosGroup/OpenCL-CTS/pull/42/files#diff-a1ec113aea425b84ea16fef7903e70a3L590), for example. This condition ends on line 606. And we only start writing to res at line 614. This means more than one work-group is going to do res[gid] = 1.

**Comment by alexbatashev** [comment]
@b-sumner the problem is that we enqueue a lot of ND-ranges. Group ID is only unique inside one ND-range. So, at the moment we have different of work-groups with the same group id.
See:
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/get_group_id.html
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/get_num_groups.html

**Comment by b-sumner** [comment]
@alexbatashev , I agree that a lot of ND-ranges are enqueued.    The original parent launches gs/ls children passing each one the group id of the original parent's work group.  The  children, on the other hand, launch only one child passing along that same original group id.  Finally at the "leaves" of this tree, where the only relevant branching occurred at the root, the only group that writes to res is the group corresponding to the original parent's group id.  So in all of those ND ranges, only one work-item ever writes to res[gid], where gid == original parent's get_group_id(0) result.

**Comment by alexbatashev** [comment]
@b-sumner Let's have a look at the picture. The Host-side program enqueues ND-range with the kernel. There are now n+1 work-groups running. Every thread group enqueues a new ND-range with block_fn and passes its id as argument. Then every work-group with ID equal to parent ID does the same thing. In the end we have n+1 ND-ranges **each** running work-groups with IDs from 0 to n. Work-item with local id 0 from every of these (n+1)*(n+1) workgroups writes to res variable. There is no condition stopping every work-group from writing to res simultaneously. My solution is to create offset, so that every work-group writes to the unique res cell.
![20190122_191226](https://user-images.githubusercontent.com/829678/51549110-cd41dd80-1e7a-11e9-951d-07ea2c249a42.jpg)

@AlexeySachkov please, correct me if I am wrong about implementation details.

**Comment by b-sumner** [comment]
@alexbatashev I see the problem now.  The leaf guard in the 2.1 and 2.2 sources only checks "lid == 0", but in the 2.0 sources from which the 2.1 and 2.2 sources were derived, the guard is "lid == 0 && gid == group_id".

I think the right fix is to make the 2.1 and 2.2 source look like the 2.0 source.  I don't really know why/how they diverged.

**Comment by alexbatashev** [comment]
@b-sumner I've verified your theory. Let's take a look at another picture. As work-groups run concurrently it is quite possible that work-group gid == 1 will be executed before wg with gid == 0. Let's imagine the stars came together in a way that this branch finishes before work-group 0 even has a chance to do anything. And now we have res[1] == 1. But sooner or later wg 0 will be executed. And it will put res[1] = 0. Despite everything is ok, we have a test failure. 
![2](https://user-images.githubusercontent.com/829678/51589509-51867600-1ef8-11e9-96e6-5d2fdbe8dfc7.jpg)

**Comment by gwawiork** [comment]
In my opinion the fix is good and adding the guard "if (lid == 0 && gid == group_id)" is not enough. See the test have to groups of cases with name containing "work_group" like enqueue_flags_wait_work_group_simple and without this string like enqueue_flags_wait_kernel_simple. Those tests no "work_group" produce only one execution tree because get_global_id(0) == 0 and here we do not have datarace issue.  However tests "work_group" starts generation multiple execution trees like in the picture https://github.com/KhronosGroup/OpenCL-CTS/issues/40#issuecomment-456463688 because of starting condition get_local_id(0) == 0
 Finally please take into account new expression to write results res[ng * group_id + gid] - each group (level 0 local work group id) has its own chance write results to array "res" because of ng*group_id what is shown in the picture https://github.com/KhronosGroup/OpenCL-CTS/issues/40#issuecomment-456696470
I build the fix on Windows and Linux , executed multiple times and results look good.

**Comment by b-sumner** [comment]
I believe the 2.0 code is correct and there are multiple conformant implementations that have evaluated it.  The only thing that needs to be done is replace the incorrect 2.1 and 2.2 source with the correct 2.0 source.

**Comment by kpet** [comment]
@alexbatashev I've spent a bit more time digging into this. I'm taking the discussion back to here as we're looking at multiple separable issues that I think we shouldn't try to resolve in one PR.

1. The code isn't the same on all branches. I think we all agree that the code on cl20_trunk is a better base. Could you open PRs to align all branches to this please?
2. Several barriers are using `CLK_LOCAL_MEM_FENCE` instead of `CLK_GLOBAL_MEM_FENCE`. I think everyone agrees on that. Could you open PRs once the ones for 1 have gone in please?
3. With 1 and 2 done, the only problem left as I understand it is that we're trying to make the test work with non-uniform NDRanges when it fundamentally hasn't been designed for that. We have each thread in the top-level kernels writing to `res` indexed with the global ID in an attempt to mask the issue and each first thread of each work-group in the leaf kernels (only in the branch where the group ID is the same all the way up to the top-level) writing to `res` indexed with the group ID. I suggest that we resolve this by only supporting uniform NDRanges for now but that we do it clearly and cleanly. I suggest we:
    * Only pass uniform NDRanges to `run_n_kernel_args` with asserts and/or comments to make this crystal clear.
    * Size `kernel_results` for the total number of work-groups instead of total number of threads and initialise it with a value that is neither 1 nor 2 (either can be produced by the leaf kernels).
    * Only write to  `res` from the leaf kernels.
    * Remove the validation code that accepts 0 as a valid result after  `global_size / local_size`.

This should solve the problems you've reported and make the code a lot easier to reason about.

**Comment by alexbatashev** [comment]
@kpet I don't understand why you mentions uniform work-groups. I think they have nothing to do with the issue. As for me, the problem is these leaves appearing at the bottom of the tree. gids of work-groups interfere with tids causing data races in certain circumstances. This is what we try to explain in https://github.com/KhronosGroup/OpenCL-CTS/issues/40#issuecomment-456696470 and https://github.com/KhronosGroup/OpenCL-CTS/issues/40#issuecomment-472438122. The original solution was to extend res array so that each leaf writes to its own cell. However, @b-sumner suggested another approach and we accepted it.

**Comment by kpet** [comment]
@alexbatashev That's one part of the problem and that one is solved by porting the changes in cl20_trunk. If this was the only issue, you wouldn't have had to change the initialisation of `kernel_results` and the presence and location of writes to it from the top-level kernels.

On non-uniform NDRanges, the thread to pull on is to try to answer the following questions:
- Why do top-level kernels initialise `res` with zeros?
- Why does the validation host code accept both 1 and 0 as valid results depending on the part of the array?
- Why is `kernel_results` sized after the number of threads rather than the number of groups?

**Comment by alexbatashev** [comment]
@kpet taking code from cl20_trunk branch does not solve the data race issue. Take any script that can run the test in loop (like [this one](https://github.com/alexbatashev/stress/blob/master/stress.py)), put some pressure and it will break. I tried different branches with different configurations and they all failed sooner or later.

The questions you asked make me think we need a completely new set of tests for the whole device execution feature. A set that will be easy to understand and maintain.

**Comment by kpet** [comment]
@alexbatashev It doesn't solve all of the races but it does solve the races between leaf kernels. Races between top-level and leaf kernels are a different issue that I believe we can solve cleanly with the approach I proposed (and simplify the code in the process).

I don't think we need to rewrite the whole test. It's not very hard to clean it and it is a valuable test. Maybe we can start with steps 1 and 2 above. I think we all agree on that and they definitely address part of the issues.
